#!/bin/sh

case "$1" in
    start)
        echo "Loading LDD modules..."
        modprobe my_custom_module
        ;;
    stop)
        echo "Unloading LDD modules..."
        rmmod my_custom_module
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0