#!/bin/sh

case "$1" in
    start)
        echo "Loading LDD modules..."
        modprobe hello
        /usr/bin/module_load faulty
        /usr/bin/scull_load
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "Unloading LDD modules..."
        rmmod hello
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        /usr/bin/aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0